upload:
  image:
    path: D:/Testdownload/
spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${upload.image.path}
  datasource:
    url: jdbc:mysql://localhost:3306/kindle
    username: root
    password: xzx123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    

    